// Seed de categorias y comunas. Se corre una vez por entorno: `npm run db:seed:taxonomia`.
//
// Conexión directa (puerto 5432), no el pooler de la app (que usa el modo transacción de Supavisor,
// sin prepared statements) — drizzle-kit necesita la conexión directa por el mismo motivo.
//
// Las 8 categorías son las que Patricio aprobó como catálogo del lanzamiento: Gasfitería,
// Electricidad, Peluquería, Limpieza, Mudanzas, Pintura, Cerrajería, Jardinería — ver el array
// `categoriasSeed` más abajo para la lista exacta.
//
// Las 346 comunas salen del código oficial SUBDERE (Decreto Exento Nº 817 del Ministerio del
// Interior), generadas desde https://github.com/knxroot/bdcut-cl en vez de transcritas a mano, para
// no arriesgar un nombre o código mal tipeado en 346 filas.
//
// Activas al sembrar: las 8 categorías, más el Gran Santiago (34 comunas: las 32 de la Provincia de
// Santiago más Puente Alto y San Bernardo, los dos conurbados que quedan fuera de esa provincia pero
// son parte del área urbana continua — la definición administrativa "Provincia de Santiago" no
// alcanza sola) y Puerto Varas — los mercados donde Patricio puede reclutar y verificar profesionales
// directamente al lanzamiento. El resto de las comunas queda en la tabla pero inactivo, listo para
// activarse cambiando el campo sin necesitar otro deploy.

import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { categorias } from '../schema/categorias'
import { comunas } from '../schema/comunas'

process.loadEnvFile('.env')

const databaseUrlDirect = process.env.DATABASE_URL_DIRECT
if (!databaseUrlDirect) {
  throw new Error('Falta DATABASE_URL_DIRECT en el entorno — ver .env.example')
}

const categoriasSeed = [
  { slug: 'gasfiteria', nombre: 'Gasfitería', activa: true },
  { slug: 'electricidad', nombre: 'Electricidad', activa: true },
  { slug: 'peluqueria', nombre: 'Peluquería', activa: true },
  { slug: 'limpieza', nombre: 'Limpieza', activa: true },
  { slug: 'mudanzas', nombre: 'Mudanzas', activa: true },
  { slug: 'pintura', nombre: 'Pintura', activa: true },
  { slug: 'cerrajeria', nombre: 'Cerrajería', activa: true },
  { slug: 'jardineria', nombre: 'Jardinería', activa: true },
]

// prettier-ignore
const comunasSeed = [
  { codigo: '1101', nombre: 'Iquique', activa: false },
  { codigo: '1107', nombre: 'Alto Hospicio', activa: false },
  { codigo: '1401', nombre: 'Pozo Almonte', activa: false },
  { codigo: '1402', nombre: 'Camiña', activa: false },
  { codigo: '1403', nombre: 'Colchane', activa: false },
  { codigo: '1404', nombre: 'Huara', activa: false },
  { codigo: '1405', nombre: 'Pica', activa: false },
  { codigo: '2101', nombre: 'Antofagasta', activa: false },
  { codigo: '2102', nombre: 'Mejillones', activa: false },
  { codigo: '2103', nombre: 'Sierra Gorda', activa: false },
  { codigo: '2104', nombre: 'Taltal', activa: false },
  { codigo: '2201', nombre: 'Calama', activa: false },
  { codigo: '2202', nombre: 'Ollagüe', activa: false },
  { codigo: '2203', nombre: 'San Pedro de Atacama', activa: false },
  { codigo: '2301', nombre: 'Tocopilla', activa: false },
  { codigo: '2302', nombre: 'María Elena', activa: false },
  { codigo: '3101', nombre: 'Copiapó', activa: false },
  { codigo: '3102', nombre: 'Caldera', activa: false },
  { codigo: '3103', nombre: 'Tierra Amarilla', activa: false },
  { codigo: '3201', nombre: 'Chañaral', activa: false },
  { codigo: '3202', nombre: 'Diego de Almagro', activa: false },
  { codigo: '3301', nombre: 'Vallenar', activa: false },
  { codigo: '3302', nombre: 'Alto del Carmen', activa: false },
  { codigo: '3303', nombre: 'Freirina', activa: false },
  { codigo: '3304', nombre: 'Huasco', activa: false },
  { codigo: '4101', nombre: 'La Serena', activa: false },
  { codigo: '4102', nombre: 'Coquimbo', activa: false },
  { codigo: '4103', nombre: 'Andacollo', activa: false },
  { codigo: '4104', nombre: 'La Higuera', activa: false },
  { codigo: '4105', nombre: 'Paihuano', activa: false },
  { codigo: '4106', nombre: 'Vicuña', activa: false },
  { codigo: '4201', nombre: 'Illapel', activa: false },
  { codigo: '4202', nombre: 'Canela', activa: false },
  { codigo: '4203', nombre: 'Los Vilos', activa: false },
  { codigo: '4204', nombre: 'Salamanca', activa: false },
  { codigo: '4301', nombre: 'Ovalle', activa: false },
  { codigo: '4302', nombre: 'Combarbalá', activa: false },
  { codigo: '4303', nombre: 'Monte Patria', activa: false },
  { codigo: '4304', nombre: 'Punitaqui', activa: false },
  { codigo: '4305', nombre: 'Río Hurtado', activa: false },
  { codigo: '5101', nombre: 'Valparaíso', activa: false },
  { codigo: '5102', nombre: 'Casablanca', activa: false },
  { codigo: '5103', nombre: 'Concón', activa: false },
  { codigo: '5104', nombre: 'Juan Fernández', activa: false },
  { codigo: '5105', nombre: 'Puchuncaví', activa: false },
  { codigo: '5107', nombre: 'Quintero', activa: false },
  { codigo: '5109', nombre: 'Viña del Mar', activa: false },
  { codigo: '5201', nombre: 'Isla de Pascua', activa: false },
  { codigo: '5301', nombre: 'Los Andes', activa: false },
  { codigo: '5302', nombre: 'Calle Larga', activa: false },
  { codigo: '5303', nombre: 'Rinconada', activa: false },
  { codigo: '5304', nombre: 'San Esteban', activa: false },
  { codigo: '5401', nombre: 'La Ligua', activa: false },
  { codigo: '5402', nombre: 'Cabildo', activa: false },
  { codigo: '5403', nombre: 'Papudo', activa: false },
  { codigo: '5404', nombre: 'Petorca', activa: false },
  { codigo: '5405', nombre: 'Zapallar', activa: false },
  { codigo: '5501', nombre: 'Quillota', activa: false },
  { codigo: '5502', nombre: 'La Calera', activa: false },
  { codigo: '5503', nombre: 'Hijuelas', activa: false },
  { codigo: '5504', nombre: 'La Cruz', activa: false },
  { codigo: '5506', nombre: 'Nogales', activa: false },
  { codigo: '5601', nombre: 'San Antonio', activa: false },
  { codigo: '5602', nombre: 'Algarrobo', activa: false },
  { codigo: '5603', nombre: 'Cartagena', activa: false },
  { codigo: '5604', nombre: 'El Quisco', activa: false },
  { codigo: '5605', nombre: 'El Tabo', activa: false },
  { codigo: '5606', nombre: 'Santo Domingo', activa: false },
  { codigo: '5701', nombre: 'San Felipe', activa: false },
  { codigo: '5702', nombre: 'Catemu', activa: false },
  { codigo: '5703', nombre: 'Llay Llay', activa: false },
  { codigo: '5704', nombre: 'Panquehue', activa: false },
  { codigo: '5705', nombre: 'Putaendo', activa: false },
  { codigo: '5706', nombre: 'Santa María', activa: false },
  { codigo: '5801', nombre: 'Quilpué', activa: false },
  { codigo: '5802', nombre: 'Limache', activa: false },
  { codigo: '5803', nombre: 'Olmué', activa: false },
  { codigo: '5804', nombre: 'Villa Alemana', activa: false },
  { codigo: '6101', nombre: 'Rancagua', activa: false },
  { codigo: '6102', nombre: 'Codegua', activa: false },
  { codigo: '6103', nombre: 'Coinco', activa: false },
  { codigo: '6104', nombre: 'Coltauco', activa: false },
  { codigo: '6105', nombre: 'Doñihue', activa: false },
  { codigo: '6106', nombre: 'Graneros', activa: false },
  { codigo: '6107', nombre: 'Las Cabras', activa: false },
  { codigo: '6108', nombre: 'Machalí', activa: false },
  { codigo: '6109', nombre: 'Malloa', activa: false },
  { codigo: '6110', nombre: 'Mostazal', activa: false },
  { codigo: '6111', nombre: 'Olivar', activa: false },
  { codigo: '6112', nombre: 'Peumo', activa: false },
  { codigo: '6113', nombre: 'Pichidegua', activa: false },
  { codigo: '6114', nombre: 'Quinta de Tilcoco', activa: false },
  { codigo: '6115', nombre: 'Rengo', activa: false },
  { codigo: '6116', nombre: 'Requínoa', activa: false },
  { codigo: '6117', nombre: 'San Vicente', activa: false },
  { codigo: '6201', nombre: 'Pichilemu', activa: false },
  { codigo: '6202', nombre: 'La Estrella', activa: false },
  { codigo: '6203', nombre: 'Litueche', activa: false },
  { codigo: '6204', nombre: 'Marchihue', activa: false },
  { codigo: '6205', nombre: 'Navidad', activa: false },
  { codigo: '6206', nombre: 'Paredones', activa: false },
  { codigo: '6301', nombre: 'San Fernando', activa: false },
  { codigo: '6302', nombre: 'Chépica', activa: false },
  { codigo: '6303', nombre: 'Chimbarongo', activa: false },
  { codigo: '6304', nombre: 'Lolol', activa: false },
  { codigo: '6305', nombre: 'Nancagua', activa: false },
  { codigo: '6306', nombre: 'Palmilla', activa: false },
  { codigo: '6307', nombre: 'Peralillo', activa: false },
  { codigo: '6308', nombre: 'Placilla', activa: false },
  { codigo: '6309', nombre: 'Pumanque', activa: false },
  { codigo: '6310', nombre: 'Santa Cruz', activa: false },
  { codigo: '7101', nombre: 'Talca', activa: false },
  { codigo: '7102', nombre: 'Constitución', activa: false },
  { codigo: '7103', nombre: 'Curepto', activa: false },
  { codigo: '7104', nombre: 'Empedrado', activa: false },
  { codigo: '7105', nombre: 'Maule', activa: false },
  { codigo: '7106', nombre: 'Pelarco', activa: false },
  { codigo: '7107', nombre: 'Pencahue', activa: false },
  { codigo: '7108', nombre: 'Río Claro', activa: false },
  { codigo: '7109', nombre: 'San Clemente', activa: false },
  { codigo: '7110', nombre: 'San Rafael', activa: false },
  { codigo: '7201', nombre: 'Cauquenes', activa: false },
  { codigo: '7202', nombre: 'Chanco', activa: false },
  { codigo: '7203', nombre: 'Pelluhue', activa: false },
  { codigo: '7301', nombre: 'Curicó', activa: false },
  { codigo: '7302', nombre: 'Hualañé', activa: false },
  { codigo: '7303', nombre: 'Licantén', activa: false },
  { codigo: '7304', nombre: 'Molina', activa: false },
  { codigo: '7305', nombre: 'Rauco', activa: false },
  { codigo: '7306', nombre: 'Romeral', activa: false },
  { codigo: '7307', nombre: 'Sagrada Familia', activa: false },
  { codigo: '7308', nombre: 'Teno', activa: false },
  { codigo: '7309', nombre: 'Vichuquén', activa: false },
  { codigo: '7401', nombre: 'Linares', activa: false },
  { codigo: '7402', nombre: 'Colbún', activa: false },
  { codigo: '7403', nombre: 'Longaví', activa: false },
  { codigo: '7404', nombre: 'Parral', activa: false },
  { codigo: '7405', nombre: 'Retiro', activa: false },
  { codigo: '7406', nombre: 'San Javier', activa: false },
  { codigo: '7407', nombre: 'Villa Alegre', activa: false },
  { codigo: '7408', nombre: 'Yerbas Buenas', activa: false },
  { codigo: '8101', nombre: 'Concepción', activa: false },
  { codigo: '8102', nombre: 'Coronel', activa: false },
  { codigo: '8103', nombre: 'Chiguayante', activa: false },
  { codigo: '8104', nombre: 'Florida', activa: false },
  { codigo: '8105', nombre: 'Hualqui', activa: false },
  { codigo: '8106', nombre: 'Lota', activa: false },
  { codigo: '8107', nombre: 'Penco', activa: false },
  { codigo: '8108', nombre: 'San Pedro de la Paz', activa: false },
  { codigo: '8109', nombre: 'Santa Juana', activa: false },
  { codigo: '8110', nombre: 'Talcahuano', activa: false },
  { codigo: '8111', nombre: 'Tomé', activa: false },
  { codigo: '8112', nombre: 'Hualpén', activa: false },
  { codigo: '8201', nombre: 'Lebu', activa: false },
  { codigo: '8202', nombre: 'Arauco', activa: false },
  { codigo: '8203', nombre: 'Cañete', activa: false },
  { codigo: '8204', nombre: 'Contulmo', activa: false },
  { codigo: '8205', nombre: 'Curanilahue', activa: false },
  { codigo: '8206', nombre: 'Los Álamos', activa: false },
  { codigo: '8207', nombre: 'Tirúa', activa: false },
  { codigo: '8301', nombre: 'Los Ángeles', activa: false },
  { codigo: '8302', nombre: 'Antuco', activa: false },
  { codigo: '8303', nombre: 'Cabrero', activa: false },
  { codigo: '8304', nombre: 'Laja', activa: false },
  { codigo: '8305', nombre: 'Mulchén', activa: false },
  { codigo: '8306', nombre: 'Nacimiento', activa: false },
  { codigo: '8307', nombre: 'Negrete', activa: false },
  { codigo: '8308', nombre: 'Quilaco', activa: false },
  { codigo: '8309', nombre: 'Quilleco', activa: false },
  { codigo: '8310', nombre: 'San Rosendo', activa: false },
  { codigo: '8311', nombre: 'Santa Bárbara', activa: false },
  { codigo: '8312', nombre: 'Tucapel', activa: false },
  { codigo: '8313', nombre: 'Yumbel', activa: false },
  { codigo: '8314', nombre: 'Alto Biobío', activa: false },
  { codigo: '8401', nombre: 'Chillán', activa: false },
  { codigo: '8402', nombre: 'Bulnes', activa: false },
  { codigo: '8403', nombre: 'Cobquecura', activa: false },
  { codigo: '8404', nombre: 'Coelemu', activa: false },
  { codigo: '8405', nombre: 'Coihueco', activa: false },
  { codigo: '8406', nombre: 'Chillán Viejo', activa: false },
  { codigo: '8407', nombre: 'El Carmen', activa: false },
  { codigo: '8408', nombre: 'Ninhue', activa: false },
  { codigo: '8409', nombre: 'Ñiquén', activa: false },
  { codigo: '8410', nombre: 'Pemuco', activa: false },
  { codigo: '8411', nombre: 'Pinto', activa: false },
  { codigo: '8412', nombre: 'Portezuelo', activa: false },
  { codigo: '8413', nombre: 'Quillón', activa: false },
  { codigo: '8414', nombre: 'Quirihue', activa: false },
  { codigo: '8415', nombre: 'Ránquil', activa: false },
  { codigo: '8416', nombre: 'San Carlos', activa: false },
  { codigo: '8417', nombre: 'San Fabián', activa: false },
  { codigo: '8418', nombre: 'San Ignacio', activa: false },
  { codigo: '8419', nombre: 'San Nicolás', activa: false },
  { codigo: '8420', nombre: 'Treguaco', activa: false },
  { codigo: '8421', nombre: 'Yungay', activa: false },
  { codigo: '9101', nombre: 'Temuco', activa: false },
  { codigo: '9102', nombre: 'Carahue', activa: false },
  { codigo: '9103', nombre: 'Cunco', activa: false },
  { codigo: '9104', nombre: 'Curarrehue', activa: false },
  { codigo: '9105', nombre: 'Freire', activa: false },
  { codigo: '9106', nombre: 'Galvarino', activa: false },
  { codigo: '9107', nombre: 'Gorbea', activa: false },
  { codigo: '9108', nombre: 'Lautaro', activa: false },
  { codigo: '9109', nombre: 'Loncoche', activa: false },
  { codigo: '9110', nombre: 'Melipeuco', activa: false },
  { codigo: '9111', nombre: 'Nueva Imperial', activa: false },
  { codigo: '9112', nombre: 'Padre las Casas', activa: false },
  { codigo: '9113', nombre: 'Perquenco', activa: false },
  { codigo: '9114', nombre: 'Pitrufquén', activa: false },
  { codigo: '9115', nombre: 'Pucón', activa: false },
  { codigo: '9116', nombre: 'Saavedra', activa: false },
  { codigo: '9117', nombre: 'Teodoro Schmidt', activa: false },
  { codigo: '9118', nombre: 'Toltén', activa: false },
  { codigo: '9119', nombre: 'Vilcún', activa: false },
  { codigo: '9120', nombre: 'Villarrica', activa: false },
  { codigo: '9121', nombre: 'Cholchol', activa: false },
  { codigo: '9201', nombre: 'Angol', activa: false },
  { codigo: '9202', nombre: 'Collipulli', activa: false },
  { codigo: '9203', nombre: 'Curacautín', activa: false },
  { codigo: '9204', nombre: 'Ercilla', activa: false },
  { codigo: '9205', nombre: 'Lonquimay', activa: false },
  { codigo: '9206', nombre: 'Los Sauces', activa: false },
  { codigo: '9207', nombre: 'Lumaco', activa: false },
  { codigo: '9208', nombre: 'Purén', activa: false },
  { codigo: '9209', nombre: 'Renaico', activa: false },
  { codigo: '9210', nombre: 'Traiguén', activa: false },
  { codigo: '9211', nombre: 'Victoria', activa: false },
  { codigo: '10101', nombre: 'Puerto Montt', activa: false },
  { codigo: '10102', nombre: 'Calbuco', activa: false },
  { codigo: '10103', nombre: 'Cochamó', activa: false },
  { codigo: '10104', nombre: 'Fresia', activa: false },
  { codigo: '10105', nombre: 'Frutillar', activa: false },
  { codigo: '10106', nombre: 'Los Muermos', activa: false },
  { codigo: '10107', nombre: 'Llanquihue', activa: false },
  { codigo: '10108', nombre: 'Maullín', activa: false },
  { codigo: '10109', nombre: 'Puerto Varas', activa: true },
  { codigo: '10201', nombre: 'Castro', activa: false },
  { codigo: '10202', nombre: 'Ancud', activa: false },
  { codigo: '10203', nombre: 'Chonchi', activa: false },
  { codigo: '10204', nombre: 'Curaco de Vélez', activa: false },
  { codigo: '10205', nombre: 'Dalcahue', activa: false },
  { codigo: '10206', nombre: 'Puqueldón', activa: false },
  { codigo: '10207', nombre: 'Queilén', activa: false },
  { codigo: '10208', nombre: 'Quellón', activa: false },
  { codigo: '10209', nombre: 'Quemchi', activa: false },
  { codigo: '10210', nombre: 'Quinchao', activa: false },
  { codigo: '10301', nombre: 'Osorno', activa: false },
  { codigo: '10302', nombre: 'Puerto Octay', activa: false },
  { codigo: '10303', nombre: 'Purranque', activa: false },
  { codigo: '10304', nombre: 'Puyehue', activa: false },
  { codigo: '10305', nombre: 'Río Negro', activa: false },
  { codigo: '10306', nombre: 'San Juan de la Costa', activa: false },
  { codigo: '10307', nombre: 'San Pablo', activa: false },
  { codigo: '10401', nombre: 'Chaitén', activa: false },
  { codigo: '10402', nombre: 'Futaleufú', activa: false },
  { codigo: '10403', nombre: 'Hualaihué', activa: false },
  { codigo: '10404', nombre: 'Palena', activa: false },
  { codigo: '11101', nombre: 'Coyhaique', activa: false },
  { codigo: '11102', nombre: 'Lago Verde', activa: false },
  { codigo: '11201', nombre: 'Aysén', activa: false },
  { codigo: '11202', nombre: 'Cisnes', activa: false },
  { codigo: '11203', nombre: 'Guaitecas', activa: false },
  { codigo: '11301', nombre: 'Cochrane', activa: false },
  { codigo: '11302', nombre: "O'Higgins", activa: false },
  { codigo: '11303', nombre: 'Tortel', activa: false },
  { codigo: '11401', nombre: 'Chile Chico', activa: false },
  { codigo: '11402', nombre: 'Río Ibáñez', activa: false },
  { codigo: '12101', nombre: 'Punta Arenas', activa: false },
  { codigo: '12102', nombre: 'Laguna Blanca', activa: false },
  { codigo: '12103', nombre: 'Río Verde', activa: false },
  { codigo: '12104', nombre: 'San Gregorio', activa: false },
  { codigo: '12201', nombre: 'Cabo de Hornos', activa: false },
  { codigo: '12202', nombre: 'Antártica', activa: false },
  { codigo: '12301', nombre: 'Porvenir', activa: false },
  { codigo: '12302', nombre: 'Primavera', activa: false },
  { codigo: '12303', nombre: 'Timaukel', activa: false },
  { codigo: '12401', nombre: 'Natales', activa: false },
  { codigo: '12402', nombre: 'Torres del Paine', activa: false },
  { codigo: '13101', nombre: 'Santiago', activa: true },
  { codigo: '13102', nombre: 'Cerrillos', activa: true },
  { codigo: '13103', nombre: 'Cerro Navia', activa: true },
  { codigo: '13104', nombre: 'Conchalí', activa: true },
  { codigo: '13105', nombre: 'El Bosque', activa: true },
  { codigo: '13106', nombre: 'Estación Central', activa: true },
  { codigo: '13107', nombre: 'Huechuraba', activa: true },
  { codigo: '13108', nombre: 'Independencia', activa: true },
  { codigo: '13109', nombre: 'La Cisterna', activa: true },
  { codigo: '13110', nombre: 'La Florida', activa: true },
  { codigo: '13111', nombre: 'La Granja', activa: true },
  { codigo: '13112', nombre: 'La Pintana', activa: true },
  { codigo: '13113', nombre: 'La Reina', activa: true },
  { codigo: '13114', nombre: 'Las Condes', activa: true },
  { codigo: '13115', nombre: 'Lo Barnechea', activa: true },
  { codigo: '13116', nombre: 'Lo Espejo', activa: true },
  { codigo: '13117', nombre: 'Lo Prado', activa: true },
  { codigo: '13118', nombre: 'Macul', activa: true },
  { codigo: '13119', nombre: 'Maipú', activa: true },
  { codigo: '13120', nombre: 'Ñuñoa', activa: true },
  { codigo: '13121', nombre: 'Pedro Aguirre Cerda', activa: true },
  { codigo: '13122', nombre: 'Peñalolén', activa: true },
  { codigo: '13123', nombre: 'Providencia', activa: true },
  { codigo: '13124', nombre: 'Pudahuel', activa: true },
  { codigo: '13125', nombre: 'Quilicura', activa: true },
  { codigo: '13126', nombre: 'Quinta Normal', activa: true },
  { codigo: '13127', nombre: 'Recoleta', activa: true },
  { codigo: '13128', nombre: 'Renca', activa: true },
  { codigo: '13129', nombre: 'San Joaquín', activa: true },
  { codigo: '13130', nombre: 'San Miguel', activa: true },
  { codigo: '13131', nombre: 'San Ramón', activa: true },
  { codigo: '13132', nombre: 'Vitacura', activa: true },
  { codigo: '13201', nombre: 'Puente Alto', activa: true },
  { codigo: '13202', nombre: 'Pirque', activa: false },
  { codigo: '13203', nombre: 'San José de Maipo', activa: false },
  { codigo: '13301', nombre: 'Colina', activa: false },
  { codigo: '13302', nombre: 'Lampa', activa: false },
  { codigo: '13303', nombre: 'Tiltil', activa: false },
  { codigo: '13401', nombre: 'San Bernardo', activa: true },
  { codigo: '13402', nombre: 'Buin', activa: false },
  { codigo: '13403', nombre: 'Calera de Tango', activa: false },
  { codigo: '13404', nombre: 'Paine', activa: false },
  { codigo: '13501', nombre: 'Melipilla', activa: false },
  { codigo: '13502', nombre: 'Alhué', activa: false },
  { codigo: '13503', nombre: 'Curacaví', activa: false },
  { codigo: '13504', nombre: 'María Pinto', activa: false },
  { codigo: '13505', nombre: 'San Pedro', activa: false },
  { codigo: '13601', nombre: 'Talagante', activa: false },
  { codigo: '13602', nombre: 'El Monte', activa: false },
  { codigo: '13603', nombre: 'Isla de Maipo', activa: false },
  { codigo: '13604', nombre: 'Padre Hurtado', activa: false },
  { codigo: '13605', nombre: 'Peñaflor', activa: false },
  { codigo: '14101', nombre: 'Valdivia', activa: false },
  { codigo: '14102', nombre: 'Corral', activa: false },
  { codigo: '14103', nombre: 'Lanco', activa: false },
  { codigo: '14104', nombre: 'Los Lagos', activa: false },
  { codigo: '14105', nombre: 'Máfil', activa: false },
  { codigo: '14106', nombre: 'Mariquina', activa: false },
  { codigo: '14107', nombre: 'Paillaco', activa: false },
  { codigo: '14108', nombre: 'Panguipulli', activa: false },
  { codigo: '14201', nombre: 'La Unión', activa: false },
  { codigo: '14202', nombre: 'Futrono', activa: false },
  { codigo: '14203', nombre: 'Lago Ranco', activa: false },
  { codigo: '14204', nombre: 'Río Bueno', activa: false },
  { codigo: '15101', nombre: 'Arica', activa: false },
  { codigo: '15102', nombre: 'Camarones', activa: false },
  { codigo: '15201', nombre: 'Putre', activa: false },
  { codigo: '15202', nombre: 'General Lagos', activa: false },
]

async function main() {
  const client = postgres(databaseUrlDirect!, { prepare: false })
  const db = drizzle({ client, schema: { categorias, comunas } })

  await db.insert(categorias).values(categoriasSeed).onConflictDoNothing()
  await db.insert(comunas).values(comunasSeed).onConflictDoNothing()

  console.log(`categorias sembradas: ${categoriasSeed.length}`)
  console.log(`comunas sembradas: ${comunasSeed.length}`)

  await client.end()
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
